
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURET = "USER_REGISTRATION_FAILURET";

export const FETCH_BUDGET_lIST_REQUEST = "FETCH_BUDGET_lIST_REQUEST";
export const FETCH_BUDGET_lIST_SUCCESS = "FETCH_BUDGET_lIST_SUCCESS";
export const FETCH_BUDGET_lIST_FAILURE = "FETCH_BUDGET_lIST_FAILURE";
export const SAVE_BUDGET_REQUEST = "SAVE_BUDGET_REQUEST";
export const SAVE_BUDGET_SUCCESS = "SAVE_BUDGET_SUCCESS";
export const SAVE_BUDGET_FAILURE = "SAVE_BUDGET_FAILURE";
export const DELETE_BUDGET_REQUEST = "DELETE_BUDGET_REQUEST";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_FAILURE = "DELETE_BUDGET_FAILURE";

export const FETCH_EXPENSE_lIST_REQUEST = "FETCH_EXPENSE_lIST_REQUEST";
export const FETCH_EXPENSE_lIST_SUCCESS = "FETCH_EXPENSE_lIST_SUCCESS";
export const FETCH_EXPENSE_lIST_FAILURE = "FETCH_EXPENSE_lIST_FAILURE";
export const SAVE_EXPENSE_REQUEST = "SAVE_EXPENSE_REQUEST";
export const SAVE_EXPENSE_SUCCESS = "SAVE_EXPENSE_SUCCESS";
export const SAVE_EXPENSE_FAILURE = "SAVE_EXPENSE_FAILURE";
export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";


export const LOGOUT = "LOGOUT";


export const SET_MAIN_PAGE = "SET_MAIN_PAGE";
export const SET_SUB_PAGE = "SET_SUB_PAGE";

export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_USER_REGISTRATION = "PAGE_USER_REGISTRATION";
export const PAGE_EXPENSE = "PAGE_EXPENSE";


export const SUB_UI_ADD_FORM = "SUB_UI_ADD_FORM";
export const SUB_UI_EDIT_FORM = "SUB_UI_EDIT_FORM"


export const ALERT_TYPE_INFO = "ALERT_TYPE_INFO";
export const ALERT_TYPE_SUCCESS = "ALERT_TYPE_SUCCESS";
export const ALERT_TYPE_WARNNG = "ALERT_TYPE_WARNNG";
export const ALERT_TYPE_ERROR = "ALERT_TYPE_ERROR";


export const DATA_VISUALIZATION_DATA_LIST = "DATA_TYPE_DATA_LIST";
export const DATA_VISUALIZATION_DAILY_EXPENSE = "DATA_TYPE_DAILY_EXPENSE";
export const DATA_VISUALIZATION_DISTRIBUTION_BY_CATEGORY = "DATA_VISUALIZATION_DISTRIBUTION_BY_CATEGORY";
export const DATA_VISUALIZATION_MONTHLY_EXPENSE_TRENDS = "DATA_TYPE_MONTHLT_EXPENSE_TRENDS";
export const DATA_VISUALIZATION_EXPENSE_OVERTIME_BY_CATEGORY = "DATA_VISUALIZATION_EXPENSE_OVERTIME_BY_CATEGORY";
export const DATA_VISUALIZATION_TOP_5_EXPENSE_CATEGORY = "DATA_TYPE_TOP_5_EXPENSE_CATEGORY";